language: java
jdk:
- openjdk8

before_install:
  - echo ${KEY_VALUE} | base64 -d > pubring.gpg
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)

deploy:
  provider: script
  script: "./gradlew deploy -Psigning.keyId=${KEY_ID} -Psigning.password=${KEY_PASS} -Psigning.secretKeyRingFile=pubring.gpg"
  skip_cleanup: true
  dry-run: false
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ (.*@[0-9]+\.[0-9]+\.[0-9]+)|(master)